<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaGenModel"
    nsURI="http://www.yakindu.org/sct/generator/BaseGenModel" nsPrefix="javaGenModel">
  <eClassifiers xsi:type="ecore:EClass" name="OutletConfigurationCustom" eSuperTypes="platform:/resource/org.yakindu.sct.model.sgen/model/emf/sgen.ecore#//OutletConfiguration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
