/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.supersteps;

import org.yakindu.sct.IStatemachine;

public interface ICycleBasedSuperStepStatemachine extends IStatemachine {
	
	public interface Interface {
	
		public void raiseE();
		
		public void raiseF();
		
		public long getX();
		
		public void setX(long value);
		
	}
	
	public Interface getInterface();
	
}
