/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.simplehierachy;

import org.yakindu.sct.IStatemachine;

public interface ISimpleHierachyStatemachine extends IStatemachine {
	
	public interface SCInterface {
	
		public void raiseEvent1();
		
	}
	
	public SCInterface getSCInterface();
	
}
