/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.nullcheck;

import org.yakindu.scr.IStatemachine;

public interface INullCheckStatemachine extends IStatemachine {
}
