/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.staticchoice;

import org.yakindu.sct.IStatemachine;

public interface IStaticChoiceStatemachine extends IStatemachine {
	
	public interface Interface {
	
		public void raiseReset();
		
		public long getNumber();
		
		public void setNumber(long value);
		
	}
	
	public Interface getInterface();
	
}
