/*
 * generated by Xtext
 */
package org.eclipselabs.mscript.language.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MscriptUiModule extends org.eclipselabs.mscript.language.ui.AbstractMscriptUiModule {
	public MscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
