/* Generated by YAKINDU Statechart Tools code generator. */
#include <string>
#include "gtest/gtest.h"
#include "RaiseEvent.h"
#include "sc_types.h"
static RaiseEvent* statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		statechart = new RaiseEvent();
		statechart->init();
	}
	virtual void TearDown() {
		delete statechart;
	}
};


TEST_F(StatemachineTest, raiseEvent) {
	
	statechart->enter();
	
	EXPECT_TRUE(statechart->isStateActive(RaiseEvent::second_region_SateA));
	
	EXPECT_TRUE(statechart->isStateActive(RaiseEvent::main_region_StateA));
	
	statechart->getDefaultSCI()->raise_e2();
	
	statechart->runCycle();
	
	statechart->runCycle();
	
	EXPECT_TRUE(statechart->isStateActive(RaiseEvent::second_region_StateB));
	
	EXPECT_TRUE(statechart->isStateActive(RaiseEvent::main_region_StateB));
	
}
