<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typesystem"
    nsURI="http://www.eclipselabs.org/mscript/TypeSystem/1.0.0" nsPrefix="typesystem">
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//PackageableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PackageableElement" abstract="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" ordered="false"
        eType="#//Namespace" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//Namespace/ownedMembers">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true" eSuperTypes="#//NamedElement">
    <eOperations name="getMember" ordered="false" lowerBound="1" eType="#//NamedElement">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" ordered="false"
        upperBound="-1" eType="#//NamedElement" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMembers" ordered="false"
        upperBound="-1" eType="#//NamedElement" changeable="false" volatile="true"
        transient="true" derived="true" eOpposite="#//NamedElement/namespace">
      <eAnnotations source="subsets" references="#//Namespace/members"/>
      <eAnnotations source="union"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" ordered="false"
        lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" ordered="false"
        upperBound="-1" eType="#//ArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensional" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multidimensional" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//Type">
    <eOperations name="evaluate" ordered="false" lowerBound="1" eType="#//DataType">
      <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
      <eParameters name="other" ordered="false" eType="#//DataType"/>
    </eOperations>
    <eOperations name="evaluatePower" ordered="false" lowerBound="1" eType="#//DataType">
      <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isAssignableFrom" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
    </eOperations>
    <eOperations name="convertTo" ordered="false" lowerBound="1" eType="#//DataType">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="Addition"/>
    <eLiterals name="Subtraction" value="1"/>
    <eLiterals name="Multiplication" value="2"/>
    <eLiterals name="Division" value="3"/>
    <eLiterals name="ElementWiseMultiplication" value="4"/>
    <eLiterals name="ElementWiseDivision" value="5"/>
    <eLiterals name="UnaryMinus" value="6"/>
    <eLiterals name="LogicalAnd" value="7"/>
    <eLiterals name="LogicalOr" value="8"/>
    <eLiterals name="LogicalNot" value="9"/>
    <eLiterals name="LessThan" value="10"/>
    <eLiterals name="LessThanOrEqualTo" value="11"/>
    <eLiterals name="GreaterThan" value="12"/>
    <eLiterals name="GreaterThanOrEqualTo" value="13"/>
    <eLiterals name="EqualTo" value="14"/>
    <eLiterals name="NotEqualTo" value="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//DataType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="evaluatePower" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluatePower"/>
        <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//NumericType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate #//PrimitiveType/%duplicates%/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="evaluatePower" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluatePower #//PrimitiveType/%duplicates%/evaluatePower"/>
        <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="isAssignableFrom" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="redefines" references="#//DataType/isAssignableFrom"/>
        <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericType" abstract="true" eSuperTypes="#//PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" ordered="false" eType="#//Unit"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit">
    <eOperations name="getFactor" ordered="false" eType="#//UnitFactor">
      <eParameters name="symbol" ordered="false" lowerBound="1" eType="#//UnitSymbol"/>
    </eOperations>
    <eOperations name="multiply" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
    </eOperations>
    <eOperations name="divide" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
    </eOperations>
    <eOperations name="power" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isSameAs" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
      <eParameters name="ignoreScale" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factors" ordered="false"
        upperBound="-1" eType="#//UnitFactor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" ordered="false"
        lowerBound="1" eType="#//UnitSymbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exponent" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitSymbol">
    <eLiterals name="Meter" literal="m"/>
    <eLiterals name="Kilogram" value="1" literal="kg"/>
    <eLiterals name="Second" value="2" literal="s"/>
    <eLiterals name="Ampere" value="3" literal="A"/>
    <eLiterals name="Kelvin" value="4" literal="K"/>
    <eLiterals name="Mole" value="5" literal="mol"/>
    <eLiterals name="Candela" value="6" literal="cd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//NumericType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate #//PrimitiveType/%duplicates%/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="evaluatePower" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluatePower #//PrimitiveType/%duplicates%/evaluatePower"/>
        <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="isAssignableFrom" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="redefines" references="#//DataType/isAssignableFrom"/>
        <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//PrimitiveType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate #//PrimitiveType/%duplicates%/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="isAssignableFrom" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="redefines" references="#//DataType/isAssignableFrom"/>
        <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="isAssignableFrom" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="redefines" references="#//DataType/isAssignableFrom"/>
        <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//Namespace #//DataType">
    <eOperations name="getLiteral" ordered="false" eType="#//EnumerationLiteral">
      <eParameters name="name" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true" eOpposite="#//EnumerationLiteral/enumeration">
      <eAnnotations source="subsets" references="#//Namespace/ownedMembers"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" ordered="false"
        lowerBound="1" eType="#//Enumeration" eOpposite="#//Enumeration/literals">
      <eAnnotations source="subsets" references="#//NamedElement/namespace"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidDataType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSystem">
    <eOperations name="getElement" ordered="false" lowerBound="1" eType="#//NamedElement">
      <eParameters name="qualifiedName" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLevelElements" ordered="false"
        upperBound="-1" eType="#//NamedElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//Namespace #//PackageableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedElements" ordered="false"
        upperBound="-1" eType="#//PackageableElement" containment="true">
      <eAnnotations source="subsets" references="#//Namespace/ownedMembers"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TensorType" eSuperTypes="#//ArrayType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EReference" name="elementType" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//ArrayType/elementType"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrix" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="#//RecordField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitType" eSuperTypes="#//DataType">
    <eAnnotations source="duplicates">
      <contents xsi:type="ecore:EOperation" name="evaluate" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluate"/>
        <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
        <eParameters name="other" ordered="false" eType="#//DataType"/>
      </contents>
      <contents xsi:type="ecore:EOperation" name="evaluatePower" ordered="false" lowerBound="1"
          eType="#//DataType">
        <eAnnotations source="redefines" references="#//DataType/evaluatePower"/>
        <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
