/* Generated by YAKINDU Statechart Tools code generator. */

#include "gtest/gtest.h"
#include "SameNameDifferentRegion.h"

#include "sc_timer_service.h"

static SameNameDifferentRegion statechart;



//! The timers are managed by a timer service. */
static sc_unit_timer_service_t timer_service;
			
class SameNameDifferentRegionTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		sameNameDifferentRegion_init(&statechart);
		sc_timer_service_init(
			&timer_service,
			0,
			(sc_run_cycle_fp) &sameNameDifferentRegion_runCycle,
			false,
			200,
			&statechart
		);
	}
};


TEST_F(SameNameDifferentRegionTest, sameNameDifferenRegionTest) {
	
	sameNameDifferentRegion_enter(&statechart);
	EXPECT_TRUE(sameNameDifferentRegion_isStateActive(&statechart, SameNameDifferentRegion_main_region_StateA));
	sameNameDifferentRegionIface_raise_e1(&statechart);
	sc_timer_service_proceed_cycles(&timer_service, 1);
	EXPECT_TRUE(sameNameDifferentRegion_isStateActive(&statechart, SameNameDifferentRegion_main_region_StateB));
	EXPECT_TRUE(sameNameDifferentRegion_isStateActive(&statechart, SameNameDifferentRegion_main_region_StateB_r1_StateA));
	sameNameDifferentRegionIface_raise_e1(&statechart);
	sc_timer_service_proceed_cycles(&timer_service, 1);
	EXPECT_TRUE(sameNameDifferentRegion_isStateActive(&statechart, SameNameDifferentRegion_main_region_StateB));
	EXPECT_TRUE(sameNameDifferentRegion_isStateActive(&statechart, SameNameDifferentRegion_main_region_StateB_r1_StateB));
}


