/*
* generated by Xtext
*/
package org.eclipselabs.mscript.language.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MscriptTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
