<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sgen"
    nsURI="http://www.yakindu.org/sct/statechart/SGen" nsPrefix="sgen">
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" eType="#//GeneratorConfiguration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statechartReferences" eType="#//StatechartReferences"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutletConfiguration" eSuperTypes="#//Configuration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="override" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GeneratorConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//Configuration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StatechartReferences">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statecharts" upperBound="-1"
        eType="ecore:EClass ../../../org.yakindu.sct.model.sgraph/model/emf/sgraph.ecore#//Statechart"/>
  </eClassifiers>
</ecore:EPackage>
