/* Generated by YAKINDU Statechart Tools code generator. */
#include "gtest/gtest.h"
#include "ConstOnlyInternalScope.h"


static ConstOnlyInternalScope statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		constOnlyInternalScope_init(&statechart);
	}
};


TEST_F(StatemachineTest, statechartEntry) {
	constOnlyInternalScope_enter(&statechart);
	EXPECT_TRUE(constOnlyInternalScope_isStateActive(&statechart, ConstOnlyInternalScope_ConstOnlyInternalScope_main_region_A));
}
TEST_F(StatemachineTest, stateTransition) {
	constOnlyInternalScope_enter(&statechart);
	constOnlyInternalScopeIface_raise_e(&statechart, 1l);
	constOnlyInternalScope_runCycle(&statechart);
	EXPECT_TRUE(constOnlyInternalScope_isStateActive(&statechart, ConstOnlyInternalScope_ConstOnlyInternalScope_main_region_B));
}


