/** Generated by YAKINDU Statechart Tools code generator. */

package org.yakindu.sct.generator.java.test;

import org.junit.*;
import static org.junit.Assert.*;
import org.yakindu.scr.shadowvalueparameter.ShadowValueParameterStatemachine;
import org.yakindu.scr.shadowvalueparameter.ShadowValueParameterStatemachine.State;	
import org.yakindu.scr.VirtualTimer;
import org.yakindu.scr.VirtualTimer.VirtualTimeTask;
import org.yakindu.scr.VirtualTimer.CycleTimeEventTask;

/**
 * Unit TestCase for ShadowValueParameter
 */
@SuppressWarnings("all")
public class ShadowValueParameter {
	
	private ShadowValueParameterStatemachine statemachine;	
	private VirtualTimer timer;
	
	
	@Before
	public void shadowValueParameter_setUp() {
		statemachine = new ShadowValueParameterStatemachine();
		timer = new VirtualTimer(200);
		timer.schedulePeriodicalTask(new CycleTimeEventTask(statemachine), 200, 200);
		
		statemachine.init();
		
	}

	@After
	public void shadowValueParameter_tearDown() {
		statemachine = null;
		
		timer = null;
	}
	
	@Test
	public void shadowValueParameterTest() {
		statemachine.enter();
		statemachine.setValue(2l);
		assertTrue((statemachine.getValue() == 2l));
		statemachine.exit();
	}
}
