/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.priorityvalues;


public class PriorityValuesStatemachine implements IPriorityValuesStatemachine {
	protected class InterfaceImpl implements Interface {
	
		private boolean event1;
		
		
		public void raiseEvent1() {
			event1 = true;
		}
		
		private boolean event2;
		
		
		public void raiseEvent2() {
			event2 = true;
		}
		
	}
	
	private static class InterfaceEvBuf {
		private boolean event1;
		private boolean event2;
	}
	private static class PriorityValuesStatemachineEvBuf {
		private InterfaceEvBuf iface = new InterfaceEvBuf();
	}
	protected InterfaceImpl defaultInterface;
	
	private boolean initialized = false;
	
	public enum State {
		SOMEREGION_A,
		SOMEREGION_B,
		MAIN_REGION_A,
		MAIN_REGION_B,
		MAIN_REGION_C,
		MAIN_REGION_D,
		MAIN_REGION_E,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[2];
	
	private int nextStateIndex;
	
	private PriorityValuesStatemachineEvBuf _current = new PriorityValuesStatemachineEvBuf();
	
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		return isExecuting;
	}
	
	protected void setIsExecuting(boolean value) {
		this.isExecuting = value;
	}
	public PriorityValuesStatemachine() {
		defaultInterface = new InterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		for (int i = 0; i < 2; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		
		isExecuting = false;
	}
	
	public void enter() {
		if (!initialized)
			throw new IllegalStateException(
			        "The state machine needs to be initialized first by calling the init() function.");
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		enterSequence_someRegion_default();
		enterSequence_main_region_default();
		isExecuting = false;
	}
	
	public void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		exitSequence_someRegion();
		exitSequence_main_region();
		isExecuting = false;
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
			        "The state machine needs to be initialized first by calling the init() function.");
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		swapInEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case SOMEREGION_A:
				someRegion_A_react(true);
				break;
			case SOMEREGION_B:
				someRegion_B_react(true);
				break;
			case MAIN_REGION_A:
				main_region_A_react(true);
				break;
			case MAIN_REGION_B:
				main_region_B_react(true);
				break;
			case MAIN_REGION_C:
				main_region_C_react(true);
				break;
			case MAIN_REGION_D:
				main_region_D_react(true);
				break;
			case MAIN_REGION_E:
				main_region_E_react(true);
				break;
			default:
				// $NULLSTATE$
			}
		}
		
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	private void swapInEvents() {
		_current.iface.event1 = defaultInterface.event1;
		defaultInterface.event1 = false;
		
		_current.iface.event2 = defaultInterface.event2;
		defaultInterface.event2 = false;
	}
	
	private void clearInEvents() {
		defaultInterface.event1 = false;
		defaultInterface.event2 = false;
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case SOMEREGION_A:
			return stateVector[0] == State.SOMEREGION_A;
		case SOMEREGION_B:
			return stateVector[0] == State.SOMEREGION_B;
		case MAIN_REGION_A:
			return stateVector[1] == State.MAIN_REGION_A;
		case MAIN_REGION_B:
			return stateVector[1] == State.MAIN_REGION_B;
		case MAIN_REGION_C:
			return stateVector[1] == State.MAIN_REGION_C;
		case MAIN_REGION_D:
			return stateVector[1] == State.MAIN_REGION_D;
		case MAIN_REGION_E:
			return stateVector[1] == State.MAIN_REGION_E;
		default:
			return false;
		}
	}
	
	public Interface getInterface() {
		return defaultInterface;
	}
	
	public void raiseEvent1() {
		defaultInterface.raiseEvent1();
	}
	
	public void raiseEvent2() {
		defaultInterface.raiseEvent2();
	}
	
	/* 'default' enter sequence for state A */
	private void enterSequence_someRegion_A_default() {
		nextStateIndex = 0;
		stateVector[0] = State.SOMEREGION_A;
	}
	
	/* 'default' enter sequence for state B */
	private void enterSequence_someRegion_B_default() {
		nextStateIndex = 0;
		stateVector[0] = State.SOMEREGION_B;
	}
	
	/* 'default' enter sequence for state A */
	private void enterSequence_main_region_A_default() {
		nextStateIndex = 1;
		stateVector[1] = State.MAIN_REGION_A;
	}
	
	/* 'default' enter sequence for state B */
	private void enterSequence_main_region_B_default() {
		nextStateIndex = 1;
		stateVector[1] = State.MAIN_REGION_B;
	}
	
	/* 'default' enter sequence for state C */
	private void enterSequence_main_region_C_default() {
		nextStateIndex = 1;
		stateVector[1] = State.MAIN_REGION_C;
	}
	
	/* 'default' enter sequence for state D */
	private void enterSequence_main_region_D_default() {
		nextStateIndex = 1;
		stateVector[1] = State.MAIN_REGION_D;
	}
	
	/* 'default' enter sequence for state E */
	private void enterSequence_main_region_E_default() {
		nextStateIndex = 1;
		stateVector[1] = State.MAIN_REGION_E;
	}
	
	/* 'default' enter sequence for region someRegion */
	private void enterSequence_someRegion_default() {
		react_someRegion__entry_Default();
	}
	
	/* 'default' enter sequence for region main region */
	private void enterSequence_main_region_default() {
		react_main_region__entry_Default();
	}
	
	/* Default exit sequence for state A */
	private void exitSequence_someRegion_A() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state B */
	private void exitSequence_someRegion_B() {
		nextStateIndex = 0;
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state A */
	private void exitSequence_main_region_A() {
		nextStateIndex = 1;
		stateVector[1] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state B */
	private void exitSequence_main_region_B() {
		nextStateIndex = 1;
		stateVector[1] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state C */
	private void exitSequence_main_region_C() {
		nextStateIndex = 1;
		stateVector[1] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state D */
	private void exitSequence_main_region_D() {
		nextStateIndex = 1;
		stateVector[1] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state E */
	private void exitSequence_main_region_E() {
		nextStateIndex = 1;
		stateVector[1] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for region someRegion */
	private void exitSequence_someRegion() {
		switch (stateVector[0]) {
		case SOMEREGION_A:
			exitSequence_someRegion_A();
			break;
		case SOMEREGION_B:
			exitSequence_someRegion_B();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region main region */
	private void exitSequence_main_region() {
		switch (stateVector[1]) {
		case MAIN_REGION_A:
			exitSequence_main_region_A();
			break;
		case MAIN_REGION_B:
			exitSequence_main_region_B();
			break;
		case MAIN_REGION_C:
			exitSequence_main_region_C();
			break;
		case MAIN_REGION_D:
			exitSequence_main_region_D();
			break;
		case MAIN_REGION_E:
			exitSequence_main_region_E();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_someRegion__entry_Default() {
		enterSequence_someRegion_A_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_main_region__entry_Default() {
		enterSequence_main_region_A_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean someRegion_A_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (_current.iface.event2) {
					exitSequence_someRegion_A();
					enterSequence_someRegion_B_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean someRegion_B_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean main_region_A_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (_current.iface.event1) {
				exitSequence_main_region_A();
				enterSequence_main_region_C_default();
			} else {
				if (_current.iface.event1) {
					exitSequence_main_region_A();
					enterSequence_main_region_B_default();
				} else {
					if (_current.iface.event1) {
						exitSequence_main_region_A();
						enterSequence_main_region_D_default();
					} else {
						if (((_current.iface.event2) && (!isStateActive(State.SOMEREGION_B)))) {
							exitSequence_main_region_A();
							enterSequence_main_region_E_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean main_region_B_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_C_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_D_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
	private boolean main_region_E_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			did_transition = false;
		}
		return did_transition;
	}
	
}
