/*
 * generated by Xtext
 */
package org.yakindu.sct.statechart;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.yakindu.sct.statechart.AbstractExpressionsRuntimeModule {

	
}
