/* Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.sct.generator.c.test;

import org.junit.Before;
import org.junit.runner.RunWith;
import org.yakindu.sct.generator.c.gtest.GTest;
import org.yakindu.sct.generator.c.gtest.GTestRunner;
import org.yakindu.sct.generator.c.gtest.GTestHelper;

@GTest(
	statechartBundle = "org.yakindu.sct.test.models",
	sourceFile = "gtests/NullCheck/NullCheckTest.cc",
	program = "gtests/NullCheck/NullCheck",
	model = "testmodels/SCTUnit/NullCheck.sct",
	additionalFilesToCopy = {
		"gtests/NullCheck/sc_timer_service.c",
		"gtests/NullCheck/sc_timer_service.h"
	},
	additionalFilesToCompile = {
		"NullCheck.c",
		"sc_timer_service.c"
	}
)
@RunWith(GTestRunner.class)
public class NullCheckTest {

	protected final GTestHelper helper = new GTestHelper(this);

	@Before
	public void setUp() {
		helper.generate();
		helper.compile();
	}
}
