/* Generated by YAKINDU Statechart Tools code generator. */
#include "gtest/gtest.h"
#include "LocalReactions.h"


static LocalReactions statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		localReactions_init(&statechart);
	}
};


TEST_F(StatemachineTest, LocalReactionsTest) {
	localReactions_enter(&statechart);
	EXPECT_TRUE(localReactions_isStateActive(&statechart, LocalReactions_main_region_A));
	localReactions_runCycle(&statechart);
	EXPECT_TRUE(localReactionsIface_get_x(&statechart)== 1l);
}


