/*
 * generated by Xtext
 */
package org.yakindu.sct.generator.model.base;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaseGenRuntimeModule extends org.yakindu.sct.generator.model.base.AbstractBaseGenRuntimeModule {

}
