<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typesystem"
    nsURI="http://www.eclipselabs.org/mscript/TypeSystem/1.0.0" nsPrefix="typesystem">
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" ordered="false"
        lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" ordered="false"
        upperBound="-1" eType="#//ArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionality" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnSize" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensional" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multidimensional" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//Type">
    <eOperations name="evaluate" ordered="false" lowerBound="1" eType="#//DataType">
      <eParameters name="operator" ordered="false" lowerBound="1" eType="#//OperatorKind"/>
      <eParameters name="other" ordered="false" eType="#//DataType"/>
    </eOperations>
    <eOperations name="evaluatePower" ordered="false" lowerBound="1" eType="#//DataType">
      <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isAssignableFrom" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//DataType"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="Addition"/>
    <eLiterals name="Subtraction" value="1"/>
    <eLiterals name="Multiplication" value="2"/>
    <eLiterals name="Division" value="3"/>
    <eLiterals name="ElementWiseMultiplication" value="4"/>
    <eLiterals name="ElementWiseDivision" value="5"/>
    <eLiterals name="UnaryMinus" value="6"/>
    <eLiterals name="LogicalAnd" value="7"/>
    <eLiterals name="LogicalOr" value="8"/>
    <eLiterals name="LogicalNot" value="9"/>
    <eLiterals name="Implies" value="10"/>
    <eLiterals name="LessThan" value="11"/>
    <eLiterals name="LessThanOrEqualTo" value="12"/>
    <eLiterals name="GreaterThan" value="13"/>
    <eLiterals name="GreaterThanOrEqualTo" value="14"/>
    <eLiterals name="EqualTo" value="15"/>
    <eLiterals name="NotEqualTo" value="16"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayDimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RealType" eSuperTypes="#//NumericType"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericType" abstract="true" eSuperTypes="#//PrimitiveType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" ordered="false" eType="#//Unit"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit">
    <eOperations name="getFactor" ordered="false" eType="#//UnitFactor">
      <eParameters name="symbol" ordered="false" lowerBound="1" eType="#//UnitSymbol"/>
    </eOperations>
    <eOperations name="multiply" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
    </eOperations>
    <eOperations name="divide" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
    </eOperations>
    <eOperations name="power" ordered="false" lowerBound="1" eType="#//Unit">
      <eParameters name="exponent" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isSameAs" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="other" ordered="false" lowerBound="1" eType="#//Unit"/>
      <eParameters name="ignoreScale" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factors" ordered="false"
        upperBound="-1" eType="#//UnitFactor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" ordered="false"
        lowerBound="1" eType="#//UnitSymbol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exponent" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitSymbol">
    <eLiterals name="Meter" literal="m"/>
    <eLiterals name="Kilogram" value="1" literal="kg"/>
    <eLiterals name="Second" value="2" literal="s"/>
    <eLiterals name="Ampere" value="3" literal="A"/>
    <eLiterals name="Kelvin" value="4" literal="K"/>
    <eLiterals name="Mole" value="5" literal="mol"/>
    <eLiterals name="Candela" value="6" literal="cd"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//NumericType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvalidDataType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="TensorType" eSuperTypes="#//ArrayType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vector" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matrix" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Record" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" lowerBound="1"
        upperBound="-1" eType="#//RecordField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RecordField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" lowerBound="1"
        eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyDataType" eSuperTypes="#//DataType"/>
</ecore:EPackage>
