/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.finalstate;

import org.yakindu.sct.IStatemachine;

public interface IFinalStateStatemachine extends IStatemachine {
}
