/* Generated by YAKINDU Statechart Tools code generator. */
#include <string>
#include "gtest/gtest.h"
#include "TransitionWithoutCondition.h"
#include "sc_types.h"
static TransitionWithoutCondition* statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		statechart = new TransitionWithoutCondition();
		statechart->init();
	}
	virtual void TearDown() {
		delete statechart;
	}
};


TEST_F(StatemachineTest, TransitionWithoutConditionTest) {
	
	statechart->enter();
	
	EXPECT_TRUE(statechart->isStateActive(TransitionWithoutCondition::main_region_A));
	
	statechart->runCycle();
	
	EXPECT_TRUE(statechart->isStateActive(TransitionWithoutCondition::main_region_B));
	
}
