/* Generated by YAKINDU Statechart Tools code generator. */

#include "gtest/gtest.h"
#include "EventDrivenOutEvents.h"

#include "sc_timer_service.h"


static EventDrivenOutEvents statechart;


//! The timers are managed by a timer service. */
static sc_unit_timer_service_t timer_service;
			
class EventDrivenOutEventsTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		eventDrivenOutEvents_init(&statechart);
		sc_timer_service_init(
			&timer_service,
			0,
			(sc_run_cycle_fp) &eventDrivenOutEvents_runCycle,
			true,
			200,
			&statechart
		);
	}
};


TEST_F(EventDrivenOutEventsTest, test) {
	
	eventDrivenOutEvents_enter(&statechart);
	EXPECT_TRUE(eventDrivenOutEvents_isStateActive(&statechart, EventDrivenOutEvents_main_region_StateA));
	EXPECT_TRUE(eventDrivenOutEvents_isStateActive(&statechart, EventDrivenOutEvents_second_region_StateC));
	eventDrivenOutEventsIface_raise_e1(&statechart);
	EXPECT_TRUE(eventDrivenOutEvents_isStateActive(&statechart, EventDrivenOutEvents_main_region_StateB));
	EXPECT_TRUE(eventDrivenOutEvents_isStateActive(&statechart, EventDrivenOutEvents_second_region_StateD));
	eventDrivenOutEvents_exit(&statechart);
}


