/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.scr.eventdriven;

import org.yakindu.sct.IStatemachine;

public interface INoLocalEventsStatemachine extends IStatemachine {
	
	public interface SCInterface {
	
		public void raiseE();
		
		public void raiseI(long value);
		
		public long getX();
		
		public void setX(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
