/* Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.sct.generator.c.test;

import java.util.List;

import org.junit.Before;
import org.yakindu.sct.generator.c.gtest.GTestHelper;

public class PedanticNoLocalEventsTest extends NoLocalEventsTest {

	protected final GTestHelper helperUnused = new GTestHelper(this) {
		@Override
		protected List<String> createCommand() {
			List<String> command = super.createCommand();
			command.add("-Wunused-function");
			command.add("-Werror=unused-function");
			return command;
		};
	};

	@Override
	@Before
	public void setUp() {
		helperUnused.generate();
		helperUnused.compile();
	}
}
