/* Generated by YAKINDU Statechart Tools code generator. */
#include <string>
#include "gtest/gtest.h"
#include "Parenthesis.h"
#include "sc_types.h"
static Parenthesis* statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		statechart = new Parenthesis();
		statechart->init();
	}
	virtual void TearDown() {
		delete statechart;
	}
};


TEST_F(StatemachineTest, simple) {
	
	statechart->enter();
	
	EXPECT_TRUE(statechart->isStateActive(Parenthesis::mainRegion_A));
	
	EXPECT_TRUE(statechart->getDefaultSCI()->get_erg()== 8l);
	
}
