/* Generated by YAKINDU Statechart Tools code generator. */
#include "gtest/gtest.h"
#include "Parenthesis.h"


static Parenthesis statechart;


class StatemachineTest : public ::testing::Test{
	protected:
	virtual void SetUp() {
		parenthesis_init(&statechart);
	}
};


TEST_F(StatemachineTest, simple) {
	parenthesis_enter(&statechart);
	EXPECT_TRUE(parenthesis_isStateActive(&statechart, Parenthesis_mainRegion_A));
	EXPECT_TRUE(parenthesisIface_get_erg(&statechart)== 8l);
}


